kind = "DojoContract"
class_hash = "0x27d7f3933ab31e09d4ea1e2051e0f6c8883d19545b50e1962febc7a44be6a5c"
original_class_hash = "0x27d7f3933ab31e09d4ea1e2051e0f6c8883d19545b50e1962febc7a44be6a5c"
base_class_hash = "0x0"
abi = "manifests/slotdev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
