kind = "DojoModel"
class_hash = "0x49fd8c80e030f71c1cba2bf64079b1dc176949dc82f140fb92940ef55af5f71"
original_class_hash = "0x49fd8c80e030f71c1cba2bf64079b1dc176949dc82f140fb92940ef55af5f71"
abi = "manifests/dev/base/abis/models/zkube-Settings-161104df.json"
tag = "zkube-Settings"
qualified_path = "zkube::models::index::settings"
manifest_name = "zkube-Settings-161104df"

[[members]]
name = "id"
type = "u8"
key = true

[[members]]
name = "is_set"
type = "bool"
key = false

[[members]]
name = "zkorp_address"
type = "felt252"
key = false

[[members]]
name = "erc721_address"
type = "felt252"
key = false
