[world]
name = "zKube"
description = "Reversed tetris fully onchain."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://app.zkube.xyz"
seed = "zKube2"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube"

[env]
rpc_url = "https://api.cartridge.gg/x/zkorp-playground/katana"
account_address = "0xb125fc0090fdc75c5b8a5145c8e7eaa99725a764e386954eafee9eff80d8f1"
private_key = "0x1c50d6dbcb52ebd5cb02ec5128fe68b7bdf8f958763080fb310c2d5ead632a4"

[init_call_args]
"zkube-chest" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
"zkube-settings" = ["0x0"]
"zkube-tournament" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
"zkube-zkorp" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]

[writers]
"zkube-account" = ["zkube-Player", "zkube-Credits"]
"zkube-chest" = ["zkube-Chest", "zkube-Participation"]
"zkube-play" = ["zkube-Player", "zkube-Game", "zkube-Tournament", "zkube-Credits", "zkube-Settings", "zkube-Chest", "zkube-Participation"]
"zkube-settings" = ["zkube-Settings", "zkube-Admin"]
"zkube-tournament" = ["zkube-Tournament"]