[package]
name = "zkube"
cairo-version = "=2.8.4"
version = "1.0.0-rc.1"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo --profile dev clean && sozo --profile dev build && sozo --profile dev migrate"
slot = "sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate"
slotdev = "sozo --profile slotdev clean && sozo --profile slotdev build && sozo --profile slotdev migrate"
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --walnut"
sepoliadev1 = "sozo --profile sepoliadev1 clean && sozo --profile sepoliadev1 build && sozo --profile sepoliadev1 migrate"
sepoliadev2 = "sozo --profile sepoliadev2 clean && sozo --profile sepoliadev2 build && sozo --profile sepoliadev2 migrate"
playground = "sozo --profile playground clean && sozo --profile playground build && sozo --profile playground migrate --walnut"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria", rev = "78b0d51" }
origami_random = { git = "https://github.com/dojoengine/origami", tag = "v1.0.0-alpha.19" }
stark_vrf = { git = "https://github.com/dojoengine/stark-vrf", rev = "5a9e81e" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }

# Custom profiles
[profile.slot]
[profile.slotdev]
[profile.slottest]
[profile.sepolia]
[profile.sepoliadev1]
[profile.sepoliadev2]
[profile.playground]