kind = "DojoContract"
class_hash = "0x68a66adb6f093069600e424dd6f25a4a5e5ce7d6722c9b45798e8d78187a784"
original_class_hash = "0x68a66adb6f093069600e424dd6f25a4a5e5ce7d6722c9b45798e8d78187a784"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-minter-5ac6ce7d.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-minter"
systems = [
    "mint",
    "claim_free_mint",
    "add_free_mint",
]
manifest_name = "zkube-minter-5ac6ce7d"
