kind = "DojoContract"
class_hash = "0x42909038bcfcace7dcc1a3307fa42b5f7b4de6483ab2ce8e49a633b6fc8ada4"
original_class_hash = "0x42909038bcfcace7dcc1a3307fa42b5f7b4de6483ab2ce8e49a633b6fc8ada4"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-minter-5ac6ce7d.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-minter"
systems = [
    "mint",
    "claim_free_mint",
    "add_free_mint",
]
manifest_name = "zkube-minter-5ac6ce7d"
