kind = "DojoContract"
class_hash = "0xfafcb5faefd94b9591a0ff471b7fdb824973c2f9d9ac6e844a353522fceef1"
original_class_hash = "0xfafcb5faefd94b9591a0ff471b7fdb824973c2f9d9ac6e844a353522fceef1"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/zkube-play-19ee70b3.json"
reads = []
writes = []
init_calldata = []
tag = "zkube-play"
systems = [
    "surrender",
    "move",
    "apply_bonus",
]
manifest_name = "zkube-play-19ee70b3"
